INSERT INTO CUSTOMERS (CUSTOMER_ID, NAME, SURNAME) VALUES ( 1, 'Khaoula', 'Ichaoui');
INSERT INTO CUSTOMERS (CUSTOMER_ID, NAME, SURNAME) VALUES ( 2, 'Nicolas', 'Devevies');

INSERT INTO CURRENT_ACCOUNTS (INITIAL_CREDIT, BALANCE, CUSTOMER_ID) VALUES (200, 5000, 2);