CREATE TABLE CUSTOMERS (
CUSTOMER_ID INT AUTO_INCREMENT  PRIMARY KEY,
NAME VARCHAR(250) NOT NULL,
SURNAME VARCHAR(250) NOT NULL
);

CREATE TABLE CURRENT_ACCOUNTS (
CURRENT_ACCOUNT_ID INT AUTO_INCREMENT  PRIMARY KEY,
INITIAL_CREDIT DECIMAL(10,2),
BALANCE DECIMAL(10,2),
CUSTOMER_ID INT ,
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);

CREATE TABLE TRANSACTIONS (
TRANSACTION_ID INT AUTO_INCREMENT PRIMARY KEY,
AMOUNT DECIMAL(10,2),
CURRENT_ACCOUNT_ID INT,
FOREIGN KEY (CURRENT_ACCOUNT_ID) REFERENCES CURRENT_ACCOUNTS(CURRENT_ACCOUNT_ID)
);